[package]
name = "shamir_secret_sharing"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-ff = "0.4.1"
ark-test-curves = {version = "0.4.2", features = ["bls12_381_scalar_field", "bls12_381_curve", "ed_on_bls12_381"]}
rand = "0.8.5"
polynomials = { path = "../polynomials" }